DROP DATABASE IF EXISTS ALARMSDB;
CREATE DATABASE ALARMSDB;
USE ALARMSDB;

CREATE TABLE AGENT
    (AID CHAR(10) NOT NULL,
    Type CHAR(1) NOT NULL,
    Description VARCHAR(50) NOT NULL,
    StartDate DATE NOT NULL,
    SALID INT NOT NULL,
    PRIMARY KEY(AID),
    FOREIGN KEY(SALID) REFERENCES LOCATION(LID));

CREATE TABLE LOCATION
    (LID INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    MBAID CHAR(10) NOT NULL,
    PRIMARY KEY(LID),
    FOREIGN KEY(MBAID) REFERENCES AGENT(AID),
     UNIQUE(Name));
     
CREATE TABLE ALARM
    (ACode CHAR(8) NOT NULL,
    RBAID CHAR(10) NOT NULL,
    LALID INT NOT NULL,
    PRIMARY KEY(ACode),
    FOREIGN KEY(RBAID) REFERENCES AGENT(AID),
    FOREIGN KEY(LALID) REFERENCES LOCATION(LID));

CREATE TABLE ADDRESSES
    (ACode CHAR(8) NOT NULL,
    AID CHAR(10) NOT NULL,
    PRIMARY KEY(ACode, AID),
    FOREIGN KEY(ACode) REFERENCES ALARM(ACode),
    FOREIGN KEY(AID) REFERENCES AGENT(AID));
    