DROP DATABASE IF EXISTS MUSEUMDB;
CREATE DATABASE MUSEUMDB;
USE MUSEUMDB;

CREATE TABLE PIECE
	(PID INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Description VARCHAR(100) NOT NULL,
    CDate DATE NOT NULL,
    Tags VARCHAR(25) NOT NULL,
    PRIMARY KEY (PID));

CREATE TABLE ARTIST
	(AID INT NOT NULL,
    FName VARCHAR(25),
    LName VARCHAR(25),
    BDate DATE NOT NULL,
    PRIMARY KEY (AID));

CREATE TABLE GALLERY
	(GCode CHAR(5) NOT NULL,
    Floor INT NOT NULL,
    Description VARCHAR(100) NOT NULL,
    PRIMARY KEY (GCode));

CREATE TABLE EXHIBITION
	(eid INT NOT NULL,
    Title VARCHAR(100),
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    PRIMARY KEY (eid));
    
CREATE TABLE SHOWCASE
	(Seid INT NOT NULL,
    SPID INT NOT NULL,
    PRIMARY KEY (Seid, SPID),
    FOREIGN KEY (Seid) REFERENCES EXHIBITION (eid),
    FOREIGN KEY (SPID) REFERENCES PIECE (PID));