DROP DATABASE CONGRESS;
CREATE DATABASE CONGRESS;
USE CONGRESS; #Default DB 

CREATE TABLE STATE
    (Name VARCHAR(25) NOT NULL,
    Region VARCHAR(25) NOT NULL,
    PRIMARY KEY(Name));

CREATE TABLE CONGRESSMEMBER
    (DISTRICTID CHAR(4) NOT NULL,
    Name VARCHAR(25) NOT NULL, 
    Affiliation CHAR(1) NOT NULL,
    StartDate DATE NOT NULL,
    StateName VARCHAR(25) NOT NULL,
    PRIMARY KEY(DISTRICTID),
    FOREIGN KEY(StateName) REFERENCES STATE(NAME));

CREATE TABLE SERVES
	(CommName VARCHAR(25) NOT NULL,
     CDID CHAR(4) NOT NULL,
     PRIMARY KEY(CommName,CDID),
     FOREIGN KEY(CommName) REFERENCES COMMITTEE(Name),
     FOREIGN KEY(CDID) REFERENCES CONGRESSMEMBER(DISTRICTID));

CREATE TABLE COMMITTEE
	(Name VARCHAR(25) NOT NULL,
     Purpose VARCHAR(100) NOT NULL, 
     Est_Date DATE NOT NULL,
     ChairDID CHAR(4) NOT NULL,
     PRIMARY KEY(Name),
     FOREIGN KEY(ChairDID) REFERENCES CONGRESSMEMBER(DISTRICTID));

CREATE TABLE UNDERTAKES
    (CommName VARCHAR(25) NOT NULL,
     BName VARCHAR(25) NOT NULL,
     Releases BIT NOT NULL,
     PRIMARY KEY(CommName,BName),
     FOREIGN KEY(CommName) REFERENCES COMMITTEE(Name),
     FOREIGN KEY(BName) REFERENCES BILL(Name));

CREATE TABLE BILL
	(Name VARCHAR(25) NOT NULL,
     DOV DATE NOT NULL,
     Passed BIT NOT NULL,
     StateName VARCHAR(25) NOT NULL,
     PRIMARY KEY(Name));

CREATE TABLE VOTES
	(CDID CHAR(4) NOT NULL,
     Bname CHAR(25) NOT NULL,
     Value CHAR(1) NOT NULL,
     PRIMARY KEY(CDID,Bname),
     FOREIGN KEY(CDID) REFERENCES CONGRESSMEMBER(DISTRICTID),
     FOREIGN KEY(Bname) REFERENCES BILL(Name));

CREATE TABLE SPONSORS
	(CDID CHAR(4) NOT NULL,
     Bname CHAR(25) NOT NULL,
     PRIMARY KEY(CDID,Bname),
     FOREIGN KEY(CDID) REFERENCES CONGRESSMEMBER(DISTRICTID),
     FOREIGN KEY(Bname) REFERENCES BILL(Name));